CREATE TABLE SERVICES_CARD_SAGA
(
  SAGA_ID          UUID                                NOT NULL
    CONSTRAINT SERVICES_CARD_SAGA_PK PRIMARY KEY,
  SAGA_NAME        VARCHAR                             NOT NULL,
  SAGA_STATE       VARCHAR                             NOT NULL,
  PAYLOAD          VARCHAR                             NOT NULL,
  STATUS           VARCHAR                             NOT NULL,
  CREATE_USER      VARCHAR(32)                         NOT NULL,
  CREATE_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_USER      VARCHAR(32)                         NOT NULL,
  UPDATE_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  SAGA_COMPENSATED BOOLEAN                             NOT NULL
);
CREATE TABLE SERVICES_CARD_SAGA_EVENT_STATES
(
  SAGA_EVENT_ID       UUID                                NOT NULL
    CONSTRAINT SERVICES_CARD_SAGA_EVENT_STATES_PK PRIMARY KEY,
  SAGA_ID             UUID                                NOT NULL,
  SAGA_EVENT_STATE    VARCHAR                             NOT NULL,
  SAGA_EVENT_OUTCOME  VARCHAR                             NOT NULL,
  SAGA_STEP_NUMBER    INTEGER                             NOT NULL,
  SAGA_EVENT_RESPONSE VARCHAR                             NOT NULL,
  CREATE_USER         VARCHAR(32)                         NOT NULL,
  CREATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_USER         VARCHAR(32)                         NOT NULL,
  UPDATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE SERVICES_CARD_SAGA_EVENT_STATES
  ADD CONSTRAINT SERVICES_CARD_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES SERVICES_CARD_SAGA (SAGA_ID);

CREATE TABLE SERVICES_CARD_SAGA_SHEDLOCK
(
  NAME       VARCHAR(64)  NOT NULL
    CONSTRAINT SERVICES_CARD_SAGA_SHEDLOCK_PK PRIMARY KEY,
  LOCK_UNTIL TIMESTAMP    NOT NULL,
  LOCKED_AT  TIMESTAMP    NOT NULL,
  LOCKED_BY  VARCHAR(255) NOT NULL
);
