---
apiVersion: v1
kind: Template
labels:
  template: 'services-card-saga-api-template'
metadata:
  name: 'services-card-saga-api-template'
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: services-card-saga-api-pipeline
    name: services-card-saga-api-pipeline
    namespace: c2mvws-tools
  spec:
    source:
      git:
        ref: master
        uri: 'https://github.com/bcgov/EDUC-SERVICES-CARD-SAGA-API'
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile